### ISSUE TITLE
New subdomain for telldus API

### ISSUE THREAD

**Issue by runbert** [johnlemonse/homebridge-telldus#97]
From Telldus on X/Twitter: https://twitter.com/telldus_status/status/1727274946983055762

> Those of you who are connected to http://api.telldus.com/ through, for example, HomeAssistant or your own solution must redirect to http://pa-api.telldus.com/ as soon as possible. All traffic to http://api.telldus.com/ will be shut down shortly.
> If you only use Telldus Live!, you don't need to do anything.

telldus-api has been updated to version 1.0.4 which uses the new domain (http://pa-api.telldus.com/).

We need to update to that version to continue using their service.

**Comment by mifi** [comment]
because of [semver](https://semver.org/), `"telldus-api": "^1.0.3"` also satisfies version `1.0.4`. there's no need to change this. just upgrade your local dependencies or delete your yarn.lock / package-lock.json

https://github.com/johnlemonse/homebridge-telldus/blob/7d5850e71a09be0484f6b5b0ca6a8f2040f42f2f/package.json#L29
